# Generated by Django 5.2.1 on 2025-06-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
