# Generated by Django 5.2.3 on 2025-06-19 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0003_alter_post_location_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "评论", "verbose_name_plural": "评论列表"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "帖子", "verbose_name_plural": "帖子列表"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户", "verbose_name_plural": "用户列表"},
        ),
    ]
